apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hashicorp/http-echo:0.2.3
        ports:
        - containerPort: 5678
          name: http
        args:
        - "-text=Hello World! This is Kubernetes from cluster nginx"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: test-node-affinity
                operator: In
                values:
                - test