apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ns1.yaml
  - ns2.yaml
  - deployment1.yaml
  - deployment2.yaml
  - mongo.yaml

components:
- ../patches
- ../argocd-syncwaves