apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mongodb
spec:
  databaseSecret:
    secretName: mongodb
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  version: "4.4.6"
  podTemplate:
    spec:
      resources:
        limits:
          cpu: "2"
          memory: 5Gi
        requests:
          cpu: "2"
          memory: 5Gi