---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mm-app-01
  namespace: argocd
spec:
  destination:
    namespace: mm
    server: https://kubernetes.default.svc 
  project: mm-project 
  source: 
    path: argocd-deployments/cluster-mm-app
    repoURL: git@github.com:sharhan-alhassan/azure-aks.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---