---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mm2-app-01
  namespace: argocd
spec:
  destination:
    namespace: mm2
    server: https://192.168.64.4:6443
  project: mm2-project 
  source: 
    path: argocd-deployments/cluster-mm2-app
    repoURL: git@github.com:sharhan-alhassan/azure-aks.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---