apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: ns.yaml
  target:
    version: v1
    kind: Namespace

- path: deploy.yaml
  target:
    version: v1
    kind: Deployment